server {
    listen 80;
    listen [::]:80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    server_tokens off;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.wasm$ {
        types { application/wasm wasm; }
        try_files $uri =404;
    }

    location ~ \.html$ {
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }
}
